#print("Shree Ganeshay Namah")
name = input("enter name: ")
age = float(input("enter age: "))
marks = float(input("enter marks: "))
print("welcome", name)
print("age=" , age)
print("marks=", marks)